# LOCALE
spring.mvc.locale-resolver=fixed
spring.mvc.locale=pt_BR

# PostgreSQL Database Connection Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_estacionamento
spring.datasource.username=postgres
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true

#Springdoc OpenApi & Swagger
springdoc.swagger-ui.path=/docs-estacionamento.html
springdoc.api-docs.path=/docs-estacionamento
springdoc.packagesToScan=com.rafaelfq.sistema_gestao_estacionamento.web.controller